tls:
  certificates:
    - certFile: /certs/homelab.lan+1.pem
      keyFile: /certs/homelab.lan+1-key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/homelab.lan+1.pem
        keyFile: /certs/homelab.lan+1-key.pem
